src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"api_projects_no_tasks"})
     * @Groups({"api_project_with_tasks"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Groups({"api_projects_no_tasks"})
     * @Groups({"api_project_with_tasks"})
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"api_projects_no_tasks"})
     * @Groups({"api_project_with_tasks"})
     */
    private $started_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups({"api_projects_no_tasks"})
     * @Groups({"api_project_with_tasks"})
     */
    private $ended_at;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"api_projects_no_tasks"})
     * @Groups({"api_project_with_tasks"})
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Task", mappedBy="project", orphanRemoval=true)
     * @Groups({"api_project_with_tasks"})
     */
    private $tasks;


    public function __construct()
    {
        $this->tasks = new ArrayCollection();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->started_at;
    }

    public function setStartedAt(\DateTimeInterface $started_at): self
    {
        $this->started_at = $started_at;

        return $this;
    }

    public function getEndedAt(): ?\DateTimeInterface
    {
        return $this->ended_at;
    }

    public function setEndedAt(?\DateTimeInterface $ended_at): self
    {
        $this->ended_at = $ended_at;

        return $this;
    }

    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

}

src/Entity/Task.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 */
class Task
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"api_project_with_tasks"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"api_project_with_tasks"})
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Groups({"api_project_with_tasks"})
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Project", inversedBy="tasks")
     */
    private $project;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"api_project_with_tasks"})
     */
    private $created_at;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(Project $project): self
    {
        $this->project = $project;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Manager;
use App\Entity\Project;
use App\Form\ProjectFormType;
use App\Form\ProjectStatusFormType;
use App\Repository\ProjectRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ProjectController extends AbstractController
{
    /**
     * @Route("/", name="default")
     */
    public function homePageRedirect()
    {
        return $this->redirectToRoute('project');
    }
    /**
     * @Route("/project", name="project")
     */
    public function projectListing(ProjectRepository $projectRepository, EntityManagerInterface $entityManager)
    {
        // if newly connected = > set the last login time
        if ($this->getUser() && $this->getUser() instanceof Manager){
            $this->getUser()->setLastLogin(new DateTime());
            $entityManager->flush();
        }
        $projects = $projectRepository->findAll();
        return $this->render('project/list.html.twig', [
            'projects' => $projects
        ]);
    }

    /**
     * @Route("/project/add", name="project_add")
     */
    public function addProject(Request $request, EntityManagerInterface $entityManager)
    {
        $newProject = new Project();
        $projetForm = $this->createForm(ProjectFormType::class, $newProject); 

        $projetForm->handleRequest($request);
        if ($projetForm->isSubmitted() && $projetForm->isValid()) {
            // Complete object project
            $newProject->setStartedAt(new DateTime());
            $newProject->setStatus("new");
            // Store the object in database
            $entityManager->persist($newProject);
            $entityManager->flush();
            // To redirect or others
            return $this->redirectToRoute('project');
        }
        return $this->render('project/add.html.twig', [
            'projetForm' => $projetForm->createView()
        ]);
    }

    /**
     * @Route("/project/action/{projectId}", name="project_action")
     */
    public function actionPage(int $projectId, ProjectRepository $projectRepository, Request $request, EntityManagerInterface $entityManager)
    {
        // find the project by the id 
        $currentProject = $projectRepository->find($projectId);
        // Edit the status form
        $editForm = $this->createForm(ProjectStatusFormType::class, $currentProject); 
        $editForm->handleRequest($request);
        if ($editForm->isSubmitted() && $editForm->isValid()) {
            if ($currentProject->getStatus() == 'done'){
                $currentProject->setEndedAt(new DateTime());
            }
            $entityManager->flush();
            return $this->redirectToRoute('project_action', ['projectId' => $projectId]);
        }
        return $this->render('project/action.html.twig', [
            'project' => $currentProject,
            'editForm' => $editForm->createView()
        ]);
    }
}

templates/project/action.html.twig
{% extends 'base.html.twig' %}

{% block title %} Action {% endblock %}
{% block stylesheets %}
<style>
    li{ 
    list-style-type: none;
    color: #dc3545;
    }
</style>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center my-5">
        <div class="col-6">
            <h1> Project: {{ project.name }} </h1>
            <div> Créé le: {{ project.startedAt | date("d/m/Y")}} </div>
            <div> Nombre de tâches: {{ project.tasks | length }} </div>
        </div>
        <div class="col-4">
            {# symfony form for editing #}
            {{ form_start(editForm) }}
                <div class="text-danger">
                    {{ form_errors(editForm) }}
                </div>
                {{ form_widget(editForm) }}
            {{ form_end(editForm) }}
        </div>
    </div>

    {% if project.status != 'done' %} 
    <div class="row my-3 mx-2">
        <a href="{{ path('task_add', {projectId: project.id}) }}" class="btn btn-outline-success">Ajouter une tâche</a>
    </div>
    {% endif %}

    <table class="table my-3">
        <thead class="thead-light">
            <tr class="text-center">
                <th scope="col" class="align-middle">Nom de la tâche</th>
                <th scope="col" class="align-middle">Description</th>
                <th scope="col" class="align-middle">Ajouté le</th>
            </tr>
        </thead>
        <tbody>
            {% for task in project.tasks %}
            <tr class="text-center">
                <td> {{ task.title }} </td>
                <td> {{ task.description }} </td>
                <td> {{ task.createdAt | date("d/m/Y")}} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if project.tasks is empty %}
    <div class="row justify-content-center my-3">
        <div class="col-8">
            <div class="alert alert-info"> No task created yet for this project!! </div>
        </div>
    </div>
    {% endif %}

</div>

{% endblock %}



{# form status à la main
<h5> Status du projet: </h5>
    <form class="form-inline my-2" action="{{ path('project_action', {projectId: project.id} ) }}" method="post">
    {% if project.status != 'done' %} 
    <select class="form-control" name="status">
        <option value="new" {% if project.status == 'new' %} selected {% endif %}> Nouveau </option>
        <option value="ongoing" {% if project.status == 'ongoing' %} selected {% endif %}> En cours </option>
        <option value="done" {% if project.status == 'done' %} selected {% endif %}> Terminé </option>                   
    </select>
    <input type="submit" value="Changer" class="btn btn-dark ml-2"> 
    {% else %}
    <div class="alert alert-info"> Projet est déjà terminé </div>
    {% endif %}
</form> #}

templates/project/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact Form{% endblock %}
{% block stylesheets %}
<style>
    li{ 
    list-style-type: none;
    color: #dc3545;
    }
</style>
{% endblock %}

{% block body %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-6">
        <h3 class="text-center"> Ajouter un projet </h3>
            {{ form_start(projetForm) }}
                <div class="text-danger">
                    {{ form_errors(projetForm) }}
                </div>
                {{ form_widget(projetForm) }}
            {{ form_end(projetForm) }}
        </div>
    </div>
</div>

{% endblock %}

templates/project/list.html.twig
{% extends 'base.html.twig' %}

{% block title %} Projet {% endblock %}

{% block body %}

<div class="container">
    <div class="row justify-content-center my-3">
        <h3 class="text-center">Liste de projets</h3>
    </div>
    <div class="row my-3 mx-2">
        <a href="{{ path('project_add') }}" class="btn btn-outline-success">Ajouter un projet</a>
    </div>
    <table class="table my-3">
        <thead class="thead-light">
            <tr class="text-center">
                <th scope="col" class="align-middle">Nom du projet</th>
                <th scope="col" class="align-middle">Status</th>
                <th scope="col" class="align-middle">Nb de tâches</th>
                <th scope="col" class="align-middle">Ajouté le</th>
                <th scope="col" class="align-middle">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for project in projects %}
            <tr class="text-center">
                <td> {{ project.name }} </td>
                <td> 
                {% if project.status == 'new' %}Nouveau{% endif %}
                {% if project.status == 'ongoing' %}En cours{% endif %}
                {% if project.status == 'done' %}Terminé{% endif %}
                </td>
                <td> {{ project.tasks | length }} </td>
                <td> {{ project.startedAt | date("d/m/Y")}} </td>
                <td> <a href="{{ path('project_action', {projectId: project.id}) }}" class="btn btn-outline-info"> Gérer </a> </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if projects is empty %}
    <div class="row justify-content-center my-3">
        <div class="col-8">
            <div class="alert alert-info"> No projets yet in the database!! </div>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}